### ISSUE TITLE
how to reload/update the plot

### ISSUE THREAD

**Issue by cchacons** [hyperoslo/Scatter#14]
Is there a function to reload the plot after changing the scatterPoints values?

Thanks,
Carlos

**Comment by 3lvis** [comment]
Can you try:

``` objc
[myScatterView display];
```

or

``` objc
[myScatterView setNeedsDisplay:YES];
```

Basically, calling `drawRect` again should force Scatter to reload.

**Comment by cchacons** [comment]
thanks 3lvis, [_scatterPlot setNeedsDisplay] worked !
